summon item ~ ~-5 ~ {Item:{id:oak_log}}
summon item ~ ~-5 ~ {Item:{id:oak_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_oak_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_oak_wood}}
summon item ~ ~-5 ~ {Item:{id:oak_planks}}
summon item ~ ~-5 ~ {Item:{id:oak_stairs}}
summon item ~ ~-5 ~ {Item:{id:oak_slab}}
summon item ~ ~-5 ~ {Item:{id:oak_fence}}
summon item ~ ~-5 ~ {Item:{id:oak_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:oak_door}}
summon item ~ ~-5 ~ {Item:{id:oak_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:oak_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:oak_button}}
summon item ~ ~-5 ~ {Item:{id:spruce_log}}
summon item ~ ~-5 ~ {Item:{id:spruce_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_spruce_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_spruce_wood}}
summon item ~ ~-5 ~ {Item:{id:spruce_planks}}
summon item ~ ~-5 ~ {Item:{id:spruce_stairs}}
summon item ~ ~-5 ~ {Item:{id:spruce_slab}}
summon item ~ ~-5 ~ {Item:{id:spruce_fence}}
summon item ~ ~-5 ~ {Item:{id:spruce_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:spruce_door}}
summon item ~ ~-5 ~ {Item:{id:spruce_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:spruce_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:spruce_button}}
summon item ~ ~-5 ~ {Item:{id:birch_log}}
summon item ~ ~-5 ~ {Item:{id:birch_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_birch_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_birch_wood}}
summon item ~ ~-5 ~ {Item:{id:birch_planks}}
summon item ~ ~-5 ~ {Item:{id:birch_stairs}}
summon item ~ ~-5 ~ {Item:{id:birch_slab}}
summon item ~ ~-5 ~ {Item:{id:birch_fence}}
summon item ~ ~-5 ~ {Item:{id:birch_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:birch_door}}
summon item ~ ~-5 ~ {Item:{id:birch_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:birch_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:birch_button}}
summon item ~ ~-5 ~ {Item:{id:jungle_log}}
summon item ~ ~-5 ~ {Item:{id:jungle_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_jungle_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_jungle_wood}}
summon item ~ ~-5 ~ {Item:{id:jungle_planks}}
summon item ~ ~-5 ~ {Item:{id:jungle_stairs}}
summon item ~ ~-5 ~ {Item:{id:jungle_slab}}
summon item ~ ~-5 ~ {Item:{id:jungle_fence}}
summon item ~ ~-5 ~ {Item:{id:jungle_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:jungle_door}}
summon item ~ ~-5 ~ {Item:{id:jungle_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:jungle_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:jungle_button}}
summon item ~ ~-5 ~ {Item:{id:acacia_log}}
summon item ~ ~-5 ~ {Item:{id:acacia_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_acacia_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_acacia_wood}}
summon item ~ ~-5 ~ {Item:{id:acacia_planks}}
summon item ~ ~-5 ~ {Item:{id:acacia_stairs}}
summon item ~ ~-5 ~ {Item:{id:acacia_slab}}
summon item ~ ~-5 ~ {Item:{id:acacia_fence}}
summon item ~ ~-5 ~ {Item:{id:acacia_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:acacia_door}}
summon item ~ ~-5 ~ {Item:{id:acacia_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:acacia_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:acacia_button}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_log}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_dark_oak_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_dark_oak_wood}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_planks}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_stairs}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_slab}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_fence}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_door}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_button}}
summon item ~ ~-5 ~ {Item:{id:mangrove_log}}
summon item ~ ~-5 ~ {Item:{id:mangrove_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_mangrove_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_mangrove_wood}}
summon item ~ ~-5 ~ {Item:{id:mangrove_planks}}
summon item ~ ~-5 ~ {Item:{id:mangrove_stairs}}
summon item ~ ~-5 ~ {Item:{id:mangrove_slab}}
summon item ~ ~-5 ~ {Item:{id:mangrove_fence}}
summon item ~ ~-5 ~ {Item:{id:mangrove_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:mangrove_door}}
summon item ~ ~-5 ~ {Item:{id:mangrove_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:mangrove_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:mangrove_button}}
summon item ~ ~-5 ~ {Item:{id:cherry_log}}
summon item ~ ~-5 ~ {Item:{id:cherry_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_cherry_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_cherry_wood}}
summon item ~ ~-5 ~ {Item:{id:cherry_planks}}
summon item ~ ~-5 ~ {Item:{id:cherry_stairs}}
summon item ~ ~-5 ~ {Item:{id:cherry_slab}}
summon item ~ ~-5 ~ {Item:{id:cherry_fence}}
summon item ~ ~-5 ~ {Item:{id:cherry_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:cherry_door}}
summon item ~ ~-5 ~ {Item:{id:cherry_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:cherry_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:cherry_button}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_log}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_wood}}
summon item ~ ~-5 ~ {Item:{id:stripped_pale_oak_log}}
summon item ~ ~-5 ~ {Item:{id:stripped_pale_oak_wood}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_planks}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_stairs}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_slab}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_fence}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_door}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_button}}
summon item ~ ~-5 ~ {Item:{id:bamboo_block}}
summon item ~ ~-5 ~ {Item:{id:stripped_bamboo_block}}
summon item ~ ~-5 ~ {Item:{id:bamboo_planks}}
summon item ~ ~-5 ~ {Item:{id:bamboo_mosaic}}
summon item ~ ~-5 ~ {Item:{id:bamboo_stairs}}
summon item ~ ~-5 ~ {Item:{id:bamboo_mosaic_stairs}}
summon item ~ ~-5 ~ {Item:{id:bamboo_slab}}
summon item ~ ~-5 ~ {Item:{id:bamboo_mosaic_slab}}
summon item ~ ~-5 ~ {Item:{id:bamboo_fence}}
summon item ~ ~-5 ~ {Item:{id:bamboo_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:bamboo_door}}
summon item ~ ~-5 ~ {Item:{id:bamboo_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:bamboo_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:bamboo_button}}
summon item ~ ~-5 ~ {Item:{id:crimson_stem}}
summon item ~ ~-5 ~ {Item:{id:crimson_hyphae}}
summon item ~ ~-5 ~ {Item:{id:stripped_crimson_stem}}
summon item ~ ~-5 ~ {Item:{id:stripped_crimson_hyphae}}
summon item ~ ~-5 ~ {Item:{id:crimson_planks}}
summon item ~ ~-5 ~ {Item:{id:crimson_stairs}}
summon item ~ ~-5 ~ {Item:{id:crimson_slab}}
summon item ~ ~-5 ~ {Item:{id:crimson_fence}}
summon item ~ ~-5 ~ {Item:{id:crimson_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:crimson_door}}
summon item ~ ~-5 ~ {Item:{id:crimson_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:crimson_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:crimson_button}}
summon item ~ ~-5 ~ {Item:{id:warped_stem}}
summon item ~ ~-5 ~ {Item:{id:warped_hyphae}}
summon item ~ ~-5 ~ {Item:{id:stripped_warped_stem}}
summon item ~ ~-5 ~ {Item:{id:stripped_warped_hyphae}}
summon item ~ ~-5 ~ {Item:{id:warped_planks}}
summon item ~ ~-5 ~ {Item:{id:warped_stairs}}
summon item ~ ~-5 ~ {Item:{id:warped_slab}}
summon item ~ ~-5 ~ {Item:{id:warped_fence}}
summon item ~ ~-5 ~ {Item:{id:warped_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:warped_door}}
summon item ~ ~-5 ~ {Item:{id:warped_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:warped_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:warped_button}}
summon item ~ ~-5 ~ {Item:{id:stone}}
summon item ~ ~-5 ~ {Item:{id:stone_stairs}}
summon item ~ ~-5 ~ {Item:{id:stone_slab}}
summon item ~ ~-5 ~ {Item:{id:stone_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:stone_button}}
summon item ~ ~-5 ~ {Item:{id:cobblestone}}
summon item ~ ~-5 ~ {Item:{id:cobblestone_stairs}}
summon item ~ ~-5 ~ {Item:{id:cobblestone_slab}}
summon item ~ ~-5 ~ {Item:{id:cobblestone_wall}}
summon item ~ ~-5 ~ {Item:{id:mossy_cobblestone}}
summon item ~ ~-5 ~ {Item:{id:mossy_cobblestone_stairs}}
summon item ~ ~-5 ~ {Item:{id:mossy_cobblestone_slab}}
summon item ~ ~-5 ~ {Item:{id:mossy_cobblestone_wall}}
summon item ~ ~-5 ~ {Item:{id:smooth_stone}}
summon item ~ ~-5 ~ {Item:{id:smooth_stone_slab}}
summon item ~ ~-5 ~ {Item:{id:stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:cracked_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:stone_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:stone_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:stone_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:mossy_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:mossy_stone_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:mossy_stone_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:mossy_stone_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:granite}}
summon item ~ ~-5 ~ {Item:{id:granite_stairs}}
summon item ~ ~-5 ~ {Item:{id:granite_slab}}
summon item ~ ~-5 ~ {Item:{id:granite_wall}}
summon item ~ ~-5 ~ {Item:{id:polished_granite}}
summon item ~ ~-5 ~ {Item:{id:polished_granite_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_granite_slab}}
summon item ~ ~-5 ~ {Item:{id:diorite}}
summon item ~ ~-5 ~ {Item:{id:diorite_stairs}}
summon item ~ ~-5 ~ {Item:{id:diorite_slab}}
summon item ~ ~-5 ~ {Item:{id:diorite_wall}}
summon item ~ ~-5 ~ {Item:{id:polished_diorite}}
summon item ~ ~-5 ~ {Item:{id:polished_diorite_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_diorite_slab}}
summon item ~ ~-5 ~ {Item:{id:andesite}}
summon item ~ ~-5 ~ {Item:{id:andesite_stairs}}
summon item ~ ~-5 ~ {Item:{id:andesite_slab}}
summon item ~ ~-5 ~ {Item:{id:andesite_wall}}
summon item ~ ~-5 ~ {Item:{id:polished_andesite}}
summon item ~ ~-5 ~ {Item:{id:polished_andesite_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_andesite_slab}}
summon item ~ ~-5 ~ {Item:{id:deepslate}}
summon item ~ ~-5 ~ {Item:{id:cobbled_deepslate}}
summon item ~ ~-5 ~ {Item:{id:cobbled_deepslate_stairs}}
summon item ~ ~-5 ~ {Item:{id:cobbled_deepslate_slab}}
summon item ~ ~-5 ~ {Item:{id:cobbled_deepslate_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_deepslate}}
summon item ~ ~-5 ~ {Item:{id:polished_deepslate}}
summon item ~ ~-5 ~ {Item:{id:polished_deepslate_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_deepslate_slab}}
summon item ~ ~-5 ~ {Item:{id:polished_deepslate_wall}}
summon item ~ ~-5 ~ {Item:{id:deepslate_bricks}}
summon item ~ ~-5 ~ {Item:{id:cracked_deepslate_bricks}}
summon item ~ ~-5 ~ {Item:{id:deepslate_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:deepslate_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:deepslate_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:deepslate_tiles}}
summon item ~ ~-5 ~ {Item:{id:cracked_deepslate_tiles}}
summon item ~ ~-5 ~ {Item:{id:deepslate_tile_stairs}}
summon item ~ ~-5 ~ {Item:{id:deepslate_tile_slab}}
summon item ~ ~-5 ~ {Item:{id:deepslate_tile_wall}}
summon item ~ ~-5 ~ {Item:{id:reinforced_deepslate}}
summon item ~ ~-5 ~ {Item:{id:tuff}}
summon item ~ ~-5 ~ {Item:{id:tuff_stairs}}
summon item ~ ~-5 ~ {Item:{id:tuff_slab}}
summon item ~ ~-5 ~ {Item:{id:tuff_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_tuff}}
summon item ~ ~-5 ~ {Item:{id:polished_tuff}}
summon item ~ ~-5 ~ {Item:{id:polished_tuff_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_tuff_slab}}
summon item ~ ~-5 ~ {Item:{id:polished_tuff_wall}}
summon item ~ ~-5 ~ {Item:{id:tuff_bricks}}
summon item ~ ~-5 ~ {Item:{id:tuff_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:tuff_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:tuff_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_tuff_bricks}}
summon item ~ ~-5 ~ {Item:{id:bricks}}
summon item ~ ~-5 ~ {Item:{id:brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:brick_slab}}
summon item ~ ~-5 ~ {Item:{id:brick_wall}}
summon item ~ ~-5 ~ {Item:{id:packed_mud}}
summon item ~ ~-5 ~ {Item:{id:mud_bricks}}
summon item ~ ~-5 ~ {Item:{id:mud_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:mud_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:mud_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:resin_bricks}}
summon item ~ ~-5 ~ {Item:{id:resin_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:resin_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:resin_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_resin_bricks}}
summon item ~ ~-5 ~ {Item:{id:sandstone}}
summon item ~ ~-5 ~ {Item:{id:sandstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:sandstone_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_sandstone}}
summon item ~ ~-5 ~ {Item:{id:smooth_sandstone}}
summon item ~ ~-5 ~ {Item:{id:smooth_sandstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:smooth_sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:cut_sandstone}}
summon item ~ ~-5 ~ {Item:{id:cut_sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:red_sandstone}}
summon item ~ ~-5 ~ {Item:{id:red_sandstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:red_sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:red_sandstone_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_red_sandstone}}
summon item ~ ~-5 ~ {Item:{id:smooth_red_sandstone}}
summon item ~ ~-5 ~ {Item:{id:smooth_red_sandstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:smooth_red_sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:cut_red_sandstone}}
summon item ~ ~-5 ~ {Item:{id:cut_red_sandstone_slab}}
summon item ~ ~-5 ~ {Item:{id:sea_lantern}}
summon item ~ ~-5 ~ {Item:{id:prismarine}}
summon item ~ ~-5 ~ {Item:{id:prismarine_stairs}}
summon item ~ ~-5 ~ {Item:{id:prismarine_slab}}
summon item ~ ~-5 ~ {Item:{id:prismarine_wall}}
summon item ~ ~-5 ~ {Item:{id:prismarine_bricks}}
summon item ~ ~-5 ~ {Item:{id:prismarine_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:prismarine_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:dark_prismarine}}
summon item ~ ~-5 ~ {Item:{id:dark_prismarine_stairs}}
summon item ~ ~-5 ~ {Item:{id:dark_prismarine_slab}}
summon item ~ ~-5 ~ {Item:{id:netherrack}}
summon item ~ ~-5 ~ {Item:{id:nether_bricks}}
summon item ~ ~-5 ~ {Item:{id:cracked_nether_bricks}}
summon item ~ ~-5 ~ {Item:{id:nether_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:nether_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:nether_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:nether_brick_fence}}
summon item ~ ~-5 ~ {Item:{id:chiseled_nether_bricks}}
summon item ~ ~-5 ~ {Item:{id:red_nether_bricks}}
summon item ~ ~-5 ~ {Item:{id:red_nether_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:red_nether_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:red_nether_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:basalt}}
summon item ~ ~-5 ~ {Item:{id:smooth_basalt}}
summon item ~ ~-5 ~ {Item:{id:polished_basalt}}
summon item ~ ~-5 ~ {Item:{id:blackstone}}
summon item ~ ~-5 ~ {Item:{id:gilded_blackstone}}
summon item ~ ~-5 ~ {Item:{id:blackstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:blackstone_slab}}
summon item ~ ~-5 ~ {Item:{id:blackstone_wall}}
summon item ~ ~-5 ~ {Item:{id:chiseled_polished_blackstone}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_slab}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_wall}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_button}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_bricks}}
summon item ~ ~-5 ~ {Item:{id:cracked_polished_blackstone_bricks}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:polished_blackstone_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:end_stone}}
summon item ~ ~-5 ~ {Item:{id:end_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:end_stone_brick_stairs}}
summon item ~ ~-5 ~ {Item:{id:end_stone_brick_slab}}
summon item ~ ~-5 ~ {Item:{id:end_stone_brick_wall}}
summon item ~ ~-5 ~ {Item:{id:purpur_block}}
summon item ~ ~-5 ~ {Item:{id:purpur_pillar}}
summon item ~ ~-5 ~ {Item:{id:purpur_stairs}}
summon item ~ ~-5 ~ {Item:{id:purpur_slab}}
summon item ~ ~-5 ~ {Item:{id:coal_block}}
summon item ~ ~-5 ~ {Item:{id:iron_block}}
summon item ~ ~-5 ~ {Item:{id:iron_bars}}
summon item ~ ~-5 ~ {Item:{id:iron_door}}
summon item ~ ~-5 ~ {Item:{id:iron_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:heavy_weighted_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:chain}}
summon item ~ ~-5 ~ {Item:{id:gold_block}}
summon item ~ ~-5 ~ {Item:{id:light_weighted_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:redstone_block}}
summon item ~ ~-5 ~ {Item:{id:emerald_block}}
summon item ~ ~-5 ~ {Item:{id:lapis_block}}
summon item ~ ~-5 ~ {Item:{id:diamond_block}}
summon item ~ ~-5 ~ {Item:{id:netherite_block}}
summon item ~ ~-5 ~ {Item:{id:quartz_block}}
summon item ~ ~-5 ~ {Item:{id:quartz_stairs}}
summon item ~ ~-5 ~ {Item:{id:quartz_slab}}
summon item ~ ~-5 ~ {Item:{id:chiseled_quartz_block}}
summon item ~ ~-5 ~ {Item:{id:quartz_bricks}}
summon item ~ ~-5 ~ {Item:{id:quartz_pillar}}
summon item ~ ~-5 ~ {Item:{id:smooth_quartz}}
summon item ~ ~-5 ~ {Item:{id:smooth_quartz_stairs}}
summon item ~ ~-5 ~ {Item:{id:smooth_quartz_slab}}
summon item ~ ~-5 ~ {Item:{id:amethyst_block}}
summon item ~ ~-5 ~ {Item:{id:copper_block}}
summon item ~ ~-5 ~ {Item:{id:chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:copper_grate}}
summon item ~ ~-5 ~ {Item:{id:cut_copper}}
summon item ~ ~-5 ~ {Item:{id:cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:copper_door}}
summon item ~ ~-5 ~ {Item:{id:copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper}}
summon item ~ ~-5 ~ {Item:{id:exposed_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:exposed_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:exposed_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:exposed_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper_door}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper}}
summon item ~ ~-5 ~ {Item:{id:weathered_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:weathered_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:weathered_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:weathered_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper_door}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper}}
summon item ~ ~-5 ~ {Item:{id:oxidized_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:oxidized_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:oxidized_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:oxidized_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper_door}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_block}}
summon item ~ ~-5 ~ {Item:{id:waxed_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:waxed_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:waxed_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_door}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_door}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_door}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_chiseled_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_grate}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_cut_copper}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_cut_copper_stairs}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_cut_copper_slab}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_door}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:white_wool}}
summon item ~ ~-5 ~ {Item:{id:light_gray_wool}}
summon item ~ ~-5 ~ {Item:{id:gray_wool}}
summon item ~ ~-5 ~ {Item:{id:black_wool}}
summon item ~ ~-5 ~ {Item:{id:brown_wool}}
summon item ~ ~-5 ~ {Item:{id:red_wool}}
summon item ~ ~-5 ~ {Item:{id:orange_wool}}
summon item ~ ~-5 ~ {Item:{id:yellow_wool}}
summon item ~ ~-5 ~ {Item:{id:lime_wool}}
summon item ~ ~-5 ~ {Item:{id:green_wool}}
summon item ~ ~-5 ~ {Item:{id:cyan_wool}}
summon item ~ ~-5 ~ {Item:{id:light_blue_wool}}
summon item ~ ~-5 ~ {Item:{id:blue_wool}}
summon item ~ ~-5 ~ {Item:{id:purple_wool}}
summon item ~ ~-5 ~ {Item:{id:magenta_wool}}
summon item ~ ~-5 ~ {Item:{id:pink_wool}}
summon item ~ ~-5 ~ {Item:{id:white_carpet}}
summon item ~ ~-5 ~ {Item:{id:light_gray_carpet}}
summon item ~ ~-5 ~ {Item:{id:gray_carpet}}
summon item ~ ~-5 ~ {Item:{id:black_carpet}}
summon item ~ ~-5 ~ {Item:{id:brown_carpet}}
summon item ~ ~-5 ~ {Item:{id:red_carpet}}
summon item ~ ~-5 ~ {Item:{id:orange_carpet}}
summon item ~ ~-5 ~ {Item:{id:yellow_carpet}}
summon item ~ ~-5 ~ {Item:{id:lime_carpet}}
summon item ~ ~-5 ~ {Item:{id:green_carpet}}
summon item ~ ~-5 ~ {Item:{id:cyan_carpet}}
summon item ~ ~-5 ~ {Item:{id:light_blue_carpet}}
summon item ~ ~-5 ~ {Item:{id:blue_carpet}}
summon item ~ ~-5 ~ {Item:{id:purple_carpet}}
summon item ~ ~-5 ~ {Item:{id:magenta_carpet}}
summon item ~ ~-5 ~ {Item:{id:pink_carpet}}
summon item ~ ~-5 ~ {Item:{id:terracotta}}
summon item ~ ~-5 ~ {Item:{id:white_terracotta}}
summon item ~ ~-5 ~ {Item:{id:light_gray_terracotta}}
summon item ~ ~-5 ~ {Item:{id:gray_terracotta}}
summon item ~ ~-5 ~ {Item:{id:black_terracotta}}
summon item ~ ~-5 ~ {Item:{id:brown_terracotta}}
summon item ~ ~-5 ~ {Item:{id:red_terracotta}}
summon item ~ ~-5 ~ {Item:{id:orange_terracotta}}
summon item ~ ~-5 ~ {Item:{id:yellow_terracotta}}
summon item ~ ~-5 ~ {Item:{id:lime_terracotta}}
summon item ~ ~-5 ~ {Item:{id:green_terracotta}}
summon item ~ ~-5 ~ {Item:{id:cyan_terracotta}}
summon item ~ ~-5 ~ {Item:{id:light_blue_terracotta}}
summon item ~ ~-5 ~ {Item:{id:blue_terracotta}}
summon item ~ ~-5 ~ {Item:{id:purple_terracotta}}
summon item ~ ~-5 ~ {Item:{id:magenta_terracotta}}
summon item ~ ~-5 ~ {Item:{id:pink_terracotta}}
summon item ~ ~-5 ~ {Item:{id:white_concrete}}
summon item ~ ~-5 ~ {Item:{id:light_gray_concrete}}
summon item ~ ~-5 ~ {Item:{id:gray_concrete}}
summon item ~ ~-5 ~ {Item:{id:black_concrete}}
summon item ~ ~-5 ~ {Item:{id:brown_concrete}}
summon item ~ ~-5 ~ {Item:{id:red_concrete}}
summon item ~ ~-5 ~ {Item:{id:orange_concrete}}
summon item ~ ~-5 ~ {Item:{id:yellow_concrete}}
summon item ~ ~-5 ~ {Item:{id:lime_concrete}}
summon item ~ ~-5 ~ {Item:{id:green_concrete}}
summon item ~ ~-5 ~ {Item:{id:cyan_concrete}}
summon item ~ ~-5 ~ {Item:{id:light_blue_concrete}}
summon item ~ ~-5 ~ {Item:{id:blue_concrete}}
summon item ~ ~-5 ~ {Item:{id:purple_concrete}}
summon item ~ ~-5 ~ {Item:{id:magenta_concrete}}
summon item ~ ~-5 ~ {Item:{id:pink_concrete}}
summon item ~ ~-5 ~ {Item:{id:white_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:light_gray_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:gray_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:black_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:brown_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:red_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:orange_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:yellow_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:lime_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:green_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:cyan_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:light_blue_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:blue_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:purple_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:magenta_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:pink_concrete_powder}}
summon item ~ ~-5 ~ {Item:{id:white_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:light_gray_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:gray_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:black_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:brown_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:red_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:orange_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:yellow_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:lime_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:green_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:cyan_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:light_blue_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:blue_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:purple_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:magenta_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:pink_glazed_terracotta}}
summon item ~ ~-5 ~ {Item:{id:glass}}
summon item ~ ~-5 ~ {Item:{id:tinted_glass}}
summon item ~ ~-5 ~ {Item:{id:white_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:light_gray_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:gray_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:black_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:brown_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:red_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:orange_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:yellow_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:lime_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:green_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:cyan_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:light_blue_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:blue_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:purple_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:magenta_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:pink_stained_glass}}
summon item ~ ~-5 ~ {Item:{id:glass_pane}}
summon item ~ ~-5 ~ {Item:{id:white_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:light_gray_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:gray_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:black_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:brown_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:red_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:orange_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:yellow_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:lime_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:green_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:cyan_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:light_blue_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:blue_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:purple_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:magenta_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:pink_stained_glass_pane}}
summon item ~ ~-5 ~ {Item:{id:shulker_box}}
summon item ~ ~-5 ~ {Item:{id:white_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:light_gray_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:gray_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:black_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:brown_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:red_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:orange_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:yellow_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:lime_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:green_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:cyan_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:light_blue_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:blue_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:purple_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:magenta_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:pink_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:white_bed}}
summon item ~ ~-5 ~ {Item:{id:light_gray_bed}}
summon item ~ ~-5 ~ {Item:{id:gray_bed}}
summon item ~ ~-5 ~ {Item:{id:black_bed}}
summon item ~ ~-5 ~ {Item:{id:brown_bed}}
summon item ~ ~-5 ~ {Item:{id:red_bed}}
summon item ~ ~-5 ~ {Item:{id:orange_bed}}
summon item ~ ~-5 ~ {Item:{id:yellow_bed}}
summon item ~ ~-5 ~ {Item:{id:lime_bed}}
summon item ~ ~-5 ~ {Item:{id:green_bed}}
summon item ~ ~-5 ~ {Item:{id:cyan_bed}}
summon item ~ ~-5 ~ {Item:{id:light_blue_bed}}
summon item ~ ~-5 ~ {Item:{id:blue_bed}}
summon item ~ ~-5 ~ {Item:{id:purple_bed}}
summon item ~ ~-5 ~ {Item:{id:magenta_bed}}
summon item ~ ~-5 ~ {Item:{id:pink_bed}}
summon item ~ ~-5 ~ {Item:{id:candle}}
summon item ~ ~-5 ~ {Item:{id:white_candle}}
summon item ~ ~-5 ~ {Item:{id:light_gray_candle}}
summon item ~ ~-5 ~ {Item:{id:gray_candle}}
summon item ~ ~-5 ~ {Item:{id:black_candle}}
summon item ~ ~-5 ~ {Item:{id:brown_candle}}
summon item ~ ~-5 ~ {Item:{id:red_candle}}
summon item ~ ~-5 ~ {Item:{id:orange_candle}}
summon item ~ ~-5 ~ {Item:{id:yellow_candle}}
summon item ~ ~-5 ~ {Item:{id:lime_candle}}
summon item ~ ~-5 ~ {Item:{id:green_candle}}
summon item ~ ~-5 ~ {Item:{id:cyan_candle}}
summon item ~ ~-5 ~ {Item:{id:light_blue_candle}}
summon item ~ ~-5 ~ {Item:{id:blue_candle}}
summon item ~ ~-5 ~ {Item:{id:purple_candle}}
summon item ~ ~-5 ~ {Item:{id:magenta_candle}}
summon item ~ ~-5 ~ {Item:{id:pink_candle}}
summon item ~ ~-5 ~ {Item:{id:white_banner}}
summon item ~ ~-5 ~ {Item:{id:light_gray_banner}}
summon item ~ ~-5 ~ {Item:{id:gray_banner}}
summon item ~ ~-5 ~ {Item:{id:black_banner}}
summon item ~ ~-5 ~ {Item:{id:brown_banner}}
summon item ~ ~-5 ~ {Item:{id:red_banner}}
summon item ~ ~-5 ~ {Item:{id:orange_banner}}
summon item ~ ~-5 ~ {Item:{id:yellow_banner}}
summon item ~ ~-5 ~ {Item:{id:lime_banner}}
summon item ~ ~-5 ~ {Item:{id:green_banner}}
summon item ~ ~-5 ~ {Item:{id:cyan_banner}}
summon item ~ ~-5 ~ {Item:{id:light_blue_banner}}
summon item ~ ~-5 ~ {Item:{id:blue_banner}}
summon item ~ ~-5 ~ {Item:{id:purple_banner}}
summon item ~ ~-5 ~ {Item:{id:magenta_banner}}
summon item ~ ~-5 ~ {Item:{id:pink_banner}}
summon item ~ ~-5 ~ {Item:{id:grass_block}}
summon item ~ ~-5 ~ {Item:{id:podzol}}
summon item ~ ~-5 ~ {Item:{id:mycelium}}
summon item ~ ~-5 ~ {Item:{id:dirt_path}}
summon item ~ ~-5 ~ {Item:{id:dirt}}
summon item ~ ~-5 ~ {Item:{id:coarse_dirt}}
summon item ~ ~-5 ~ {Item:{id:rooted_dirt}}
summon item ~ ~-5 ~ {Item:{id:farmland}}
summon item ~ ~-5 ~ {Item:{id:mud}}
summon item ~ ~-5 ~ {Item:{id:clay}}
summon item ~ ~-5 ~ {Item:{id:gravel}}
summon item ~ ~-5 ~ {Item:{id:sand}}
summon item ~ ~-5 ~ {Item:{id:sandstone}}
summon item ~ ~-5 ~ {Item:{id:red_sand}}
summon item ~ ~-5 ~ {Item:{id:red_sandstone}}
summon item ~ ~-5 ~ {Item:{id:ice}}
summon item ~ ~-5 ~ {Item:{id:packed_ice}}
summon item ~ ~-5 ~ {Item:{id:blue_ice}}
summon item ~ ~-5 ~ {Item:{id:snow_block}}
summon item ~ ~-5 ~ {Item:{id:snow}}
summon item ~ ~-5 ~ {Item:{id:moss_block}}
summon item ~ ~-5 ~ {Item:{id:moss_carpet}}
summon item ~ ~-5 ~ {Item:{id:pale_moss_block}}
summon item ~ ~-5 ~ {Item:{id:pale_moss_carpet}}
summon item ~ ~-5 ~ {Item:{id:pale_hanging_moss}}
summon item ~ ~-5 ~ {Item:{id:stone}}
summon item ~ ~-5 ~ {Item:{id:deepslate}}
summon item ~ ~-5 ~ {Item:{id:granite}}
summon item ~ ~-5 ~ {Item:{id:diorite}}
summon item ~ ~-5 ~ {Item:{id:andesite}}
summon item ~ ~-5 ~ {Item:{id:calcite}}
summon item ~ ~-5 ~ {Item:{id:tuff}}
summon item ~ ~-5 ~ {Item:{id:dripstone_block}}
summon item ~ ~-5 ~ {Item:{id:pointed_dripstone}}
summon item ~ ~-5 ~ {Item:{id:prismarine}}
summon item ~ ~-5 ~ {Item:{id:magma_block}}
summon item ~ ~-5 ~ {Item:{id:obsidian}}
summon item ~ ~-5 ~ {Item:{id:crying_obsidian}}
summon item ~ ~-5 ~ {Item:{id:netherrack}}
summon item ~ ~-5 ~ {Item:{id:crimson_nylium}}
summon item ~ ~-5 ~ {Item:{id:warped_nylium}}
summon item ~ ~-5 ~ {Item:{id:soul_sand}}
summon item ~ ~-5 ~ {Item:{id:soul_soil}}
summon item ~ ~-5 ~ {Item:{id:bone_block}}
summon item ~ ~-5 ~ {Item:{id:blackstone}}
summon item ~ ~-5 ~ {Item:{id:basalt}}
summon item ~ ~-5 ~ {Item:{id:smooth_basalt}}
summon item ~ ~-5 ~ {Item:{id:end_stone}}
summon item ~ ~-5 ~ {Item:{id:coal_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_coal_ore}}
summon item ~ ~-5 ~ {Item:{id:iron_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_iron_ore}}
summon item ~ ~-5 ~ {Item:{id:copper_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_copper_ore}}
summon item ~ ~-5 ~ {Item:{id:gold_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_gold_ore}}
summon item ~ ~-5 ~ {Item:{id:redstone_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_redstone_ore}}
summon item ~ ~-5 ~ {Item:{id:emerald_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_emerald_ore}}
summon item ~ ~-5 ~ {Item:{id:lapis_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_lapis_ore}}
summon item ~ ~-5 ~ {Item:{id:diamond_ore}}
summon item ~ ~-5 ~ {Item:{id:deepslate_diamond_ore}}
summon item ~ ~-5 ~ {Item:{id:nether_gold_ore}}
summon item ~ ~-5 ~ {Item:{id:nether_quartz_ore}}
summon item ~ ~-5 ~ {Item:{id:ancient_debris}}
summon item ~ ~-5 ~ {Item:{id:raw_iron_block}}
summon item ~ ~-5 ~ {Item:{id:raw_copper_block}}
summon item ~ ~-5 ~ {Item:{id:raw_gold_block}}
summon item ~ ~-5 ~ {Item:{id:glowstone}}
summon item ~ ~-5 ~ {Item:{id:amethyst_block}}
summon item ~ ~-5 ~ {Item:{id:budding_amethyst}}
summon item ~ ~-5 ~ {Item:{id:small_amethyst_bud}}
summon item ~ ~-5 ~ {Item:{id:medium_amethyst_bud}}
summon item ~ ~-5 ~ {Item:{id:large_amethyst_bud}}
summon item ~ ~-5 ~ {Item:{id:amethyst_cluster}}
summon item ~ ~-5 ~ {Item:{id:oak_log}}
summon item ~ ~-5 ~ {Item:{id:spruce_log}}
summon item ~ ~-5 ~ {Item:{id:birch_log}}
summon item ~ ~-5 ~ {Item:{id:jungle_log}}
summon item ~ ~-5 ~ {Item:{id:acacia_log}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_log}}
summon item ~ ~-5 ~ {Item:{id:mangrove_log}}
summon item ~ ~-5 ~ {Item:{id:mangrove_roots}}
summon item ~ ~-5 ~ {Item:{id:muddy_mangrove_roots}}
summon item ~ ~-5 ~ {Item:{id:cherry_log}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_log}}
summon item ~ ~-5 ~ {Item:{id:mushroom_stem}}
summon item ~ ~-5 ~ {Item:{id:crimson_stem}}
summon item ~ ~-5 ~ {Item:{id:warped_stem}}
summon item ~ ~-5 ~ {Item:{id:oak_leaves}}
summon item ~ ~-5 ~ {Item:{id:spruce_leaves}}
summon item ~ ~-5 ~ {Item:{id:birch_leaves}}
summon item ~ ~-5 ~ {Item:{id:jungle_leaves}}
summon item ~ ~-5 ~ {Item:{id:acacia_leaves}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_leaves}}
summon item ~ ~-5 ~ {Item:{id:mangrove_leaves}}
summon item ~ ~-5 ~ {Item:{id:cherry_leaves}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_leaves}}
summon item ~ ~-5 ~ {Item:{id:azalea_leaves}}
summon item ~ ~-5 ~ {Item:{id:flowering_azalea_leaves}}
summon item ~ ~-5 ~ {Item:{id:brown_mushroom_block}}
summon item ~ ~-5 ~ {Item:{id:red_mushroom_block}}
summon item ~ ~-5 ~ {Item:{id:nether_wart_block}}
summon item ~ ~-5 ~ {Item:{id:warped_wart_block}}
summon item ~ ~-5 ~ {Item:{id:shroomlight}}
summon item ~ ~-5 ~ {Item:{id:oak_sapling}}
summon item ~ ~-5 ~ {Item:{id:spruce_sapling}}
summon item ~ ~-5 ~ {Item:{id:birch_sapling}}
summon item ~ ~-5 ~ {Item:{id:jungle_sapling}}
summon item ~ ~-5 ~ {Item:{id:acacia_sapling}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_sapling}}
summon item ~ ~-5 ~ {Item:{id:mangrove_propagule}}
summon item ~ ~-5 ~ {Item:{id:cherry_sapling}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_sapling}}
summon item ~ ~-5 ~ {Item:{id:azalea}}
summon item ~ ~-5 ~ {Item:{id:flowering_azalea}}
summon item ~ ~-5 ~ {Item:{id:brown_mushroom}}
summon item ~ ~-5 ~ {Item:{id:red_mushroom}}
summon item ~ ~-5 ~ {Item:{id:crimson_fungus}}
summon item ~ ~-5 ~ {Item:{id:warped_fungus}}
summon item ~ ~-5 ~ {Item:{id:short_grass}}
summon item ~ ~-5 ~ {Item:{id:fern}}
summon item ~ ~-5 ~ {Item:{id:short_dry_grass}}
summon item ~ ~-5 ~ {Item:{id:bush}}
summon item ~ ~-5 ~ {Item:{id:dead_bush}}
summon item ~ ~-5 ~ {Item:{id:dandelion}}
summon item ~ ~-5 ~ {Item:{id:poppy}}
summon item ~ ~-5 ~ {Item:{id:blue_orchid}}
summon item ~ ~-5 ~ {Item:{id:allium}}
summon item ~ ~-5 ~ {Item:{id:azure_bluet}}
summon item ~ ~-5 ~ {Item:{id:red_tulip}}
summon item ~ ~-5 ~ {Item:{id:orange_tulip}}
summon item ~ ~-5 ~ {Item:{id:white_tulip}}
summon item ~ ~-5 ~ {Item:{id:pink_tulip}}
summon item ~ ~-5 ~ {Item:{id:oxeye_daisy}}
summon item ~ ~-5 ~ {Item:{id:cornflower}}
summon item ~ ~-5 ~ {Item:{id:lily_of_the_valley}}
summon item ~ ~-5 ~ {Item:{id:torchflower}}
summon item ~ ~-5 ~ {Item:{id:cactus_flower}}
summon item ~ ~-5 ~ {Item:{id:closed_eyeblossom}}
summon item ~ ~-5 ~ {Item:{id:open_eyeblossom}}
summon item ~ ~-5 ~ {Item:{id:wither_rose}}
summon item ~ ~-5 ~ {Item:{id:pink_petals}}
summon item ~ ~-5 ~ {Item:{id:wildflowers}}
summon item ~ ~-5 ~ {Item:{id:leaf_litter}}
summon item ~ ~-5 ~ {Item:{id:spore_blossom}}
summon item ~ ~-5 ~ {Item:{id:firefly_bush}}
summon item ~ ~-5 ~ {Item:{id:bamboo}}
summon item ~ ~-5 ~ {Item:{id:sugar_cane}}
summon item ~ ~-5 ~ {Item:{id:cactus}}
summon item ~ ~-5 ~ {Item:{id:crimson_roots}}
summon item ~ ~-5 ~ {Item:{id:warped_roots}}
summon item ~ ~-5 ~ {Item:{id:nether_sprouts}}
summon item ~ ~-5 ~ {Item:{id:weeping_vines}}
summon item ~ ~-5 ~ {Item:{id:twisting_vines}}
summon item ~ ~-5 ~ {Item:{id:vine}}
summon item ~ ~-5 ~ {Item:{id:tall_grass}}
summon item ~ ~-5 ~ {Item:{id:large_fern}}
summon item ~ ~-5 ~ {Item:{id:tall_dry_grass}}
summon item ~ ~-5 ~ {Item:{id:sunflower}}
summon item ~ ~-5 ~ {Item:{id:lilac}}
summon item ~ ~-5 ~ {Item:{id:rose_bush}}
summon item ~ ~-5 ~ {Item:{id:peony}}
summon item ~ ~-5 ~ {Item:{id:pitcher_plant}}
summon item ~ ~-5 ~ {Item:{id:big_dripleaf}}
summon item ~ ~-5 ~ {Item:{id:small_dripleaf}}
summon item ~ ~-5 ~ {Item:{id:chorus_plant}}
summon item ~ ~-5 ~ {Item:{id:chorus_flower}}
summon item ~ ~-5 ~ {Item:{id:glow_lichen}}
summon item ~ ~-5 ~ {Item:{id:hanging_roots}}
summon item ~ ~-5 ~ {Item:{id:frogspawn}}
summon item ~ ~-5 ~ {Item:{id:turtle_egg}}
summon item ~ ~-5 ~ {Item:{id:sniffer_egg}}
summon item ~ ~-5 ~ {Item:{id:dried_ghast}}
summon item ~ ~-5 ~ {Item:{id:wheat_seeds}}
summon item ~ ~-5 ~ {Item:{id:cocoa_beans}}
summon item ~ ~-5 ~ {Item:{id:pumpkin_seeds}}
summon item ~ ~-5 ~ {Item:{id:melon_seeds}}
summon item ~ ~-5 ~ {Item:{id:beetroot_seeds}}
summon item ~ ~-5 ~ {Item:{id:torchflower_seeds}}
summon item ~ ~-5 ~ {Item:{id:pitcher_pod}}
summon item ~ ~-5 ~ {Item:{id:glow_berries}}
summon item ~ ~-5 ~ {Item:{id:sweet_berries}}
summon item ~ ~-5 ~ {Item:{id:nether_wart}}
summon item ~ ~-5 ~ {Item:{id:lily_pad}}
summon item ~ ~-5 ~ {Item:{id:seagrass}}
summon item ~ ~-5 ~ {Item:{id:sea_pickle}}
summon item ~ ~-5 ~ {Item:{id:kelp}}
summon item ~ ~-5 ~ {Item:{id:dried_kelp_block}}
summon item ~ ~-5 ~ {Item:{id:tube_coral_block}}
summon item ~ ~-5 ~ {Item:{id:brain_coral_block}}
summon item ~ ~-5 ~ {Item:{id:bubble_coral_block}}
summon item ~ ~-5 ~ {Item:{id:fire_coral_block}}
summon item ~ ~-5 ~ {Item:{id:horn_coral_block}}
summon item ~ ~-5 ~ {Item:{id:dead_tube_coral_block}}
summon item ~ ~-5 ~ {Item:{id:dead_brain_coral_block}}
summon item ~ ~-5 ~ {Item:{id:dead_bubble_coral_block}}
summon item ~ ~-5 ~ {Item:{id:dead_fire_coral_block}}
summon item ~ ~-5 ~ {Item:{id:dead_horn_coral_block}}
summon item ~ ~-5 ~ {Item:{id:tube_coral}}
summon item ~ ~-5 ~ {Item:{id:brain_coral}}
summon item ~ ~-5 ~ {Item:{id:bubble_coral}}
summon item ~ ~-5 ~ {Item:{id:fire_coral}}
summon item ~ ~-5 ~ {Item:{id:horn_coral}}
summon item ~ ~-5 ~ {Item:{id:dead_tube_coral}}
summon item ~ ~-5 ~ {Item:{id:dead_brain_coral}}
summon item ~ ~-5 ~ {Item:{id:dead_bubble_coral}}
summon item ~ ~-5 ~ {Item:{id:dead_fire_coral}}
summon item ~ ~-5 ~ {Item:{id:dead_horn_coral}}
summon item ~ ~-5 ~ {Item:{id:tube_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:brain_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:bubble_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:fire_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:horn_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:dead_tube_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:dead_brain_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:dead_bubble_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:dead_fire_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:dead_horn_coral_fan}}
summon item ~ ~-5 ~ {Item:{id:sponge}}
summon item ~ ~-5 ~ {Item:{id:wet_sponge}}
summon item ~ ~-5 ~ {Item:{id:melon}}
summon item ~ ~-5 ~ {Item:{id:pumpkin}}
summon item ~ ~-5 ~ {Item:{id:carved_pumpkin}}
summon item ~ ~-5 ~ {Item:{id:jack_o_lantern}}
summon item ~ ~-5 ~ {Item:{id:hay_block}}
summon item ~ ~-5 ~ {Item:{id:bee_nest}}
summon item ~ ~-5 ~ {Item:{id:honeycomb_block}}
summon item ~ ~-5 ~ {Item:{id:slime_block}}
summon item ~ ~-5 ~ {Item:{id:honey_block}}
summon item ~ ~-5 ~ {Item:{id:resin_block}}
summon item ~ ~-5 ~ {Item:{id:ochre_froglight}}
summon item ~ ~-5 ~ {Item:{id:verdant_froglight}}
summon item ~ ~-5 ~ {Item:{id:pearlescent_froglight}}
summon item ~ ~-5 ~ {Item:{id:sculk}}
summon item ~ ~-5 ~ {Item:{id:sculk_vein}}
summon item ~ ~-5 ~ {Item:{id:sculk_catalyst}}
summon item ~ ~-5 ~ {Item:{id:sculk_shrieker}}
summon item ~ ~-5 ~ {Item:{id:sculk_sensor}}
summon item ~ ~-5 ~ {Item:{id:cobweb}}
summon item ~ ~-5 ~ {Item:{id:bedrock}}
summon item ~ ~-5 ~ {Item:{id:torch}}
summon item ~ ~-5 ~ {Item:{id:soul_torch}}
summon item ~ ~-5 ~ {Item:{id:redstone_torch}}
summon item ~ ~-5 ~ {Item:{id:lantern}}
summon item ~ ~-5 ~ {Item:{id:soul_lantern}}
summon item ~ ~-5 ~ {Item:{id:chain}}
summon item ~ ~-5 ~ {Item:{id:end_rod}}
summon item ~ ~-5 ~ {Item:{id:sea_lantern}}
summon item ~ ~-5 ~ {Item:{id:redstone_lamp}}
summon item ~ ~-5 ~ {Item:{id:copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:exposed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:weathered_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:oxidized_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:glowstone}}
summon item ~ ~-5 ~ {Item:{id:shroomlight}}
summon item ~ ~-5 ~ {Item:{id:ochre_froglight}}
summon item ~ ~-5 ~ {Item:{id:verdant_froglight}}
summon item ~ ~-5 ~ {Item:{id:pearlescent_froglight}}
summon item ~ ~-5 ~ {Item:{id:crying_obsidian}}
summon item ~ ~-5 ~ {Item:{id:glow_lichen}}
summon item ~ ~-5 ~ {Item:{id:magma_block}}
summon item ~ ~-5 ~ {Item:{id:crafting_table}}
summon item ~ ~-5 ~ {Item:{id:stonecutter}}
summon item ~ ~-5 ~ {Item:{id:cartography_table}}
summon item ~ ~-5 ~ {Item:{id:fletching_table}}
summon item ~ ~-5 ~ {Item:{id:smithing_table}}
summon item ~ ~-5 ~ {Item:{id:grindstone}}
summon item ~ ~-5 ~ {Item:{id:loom}}
summon item ~ ~-5 ~ {Item:{id:furnace}}
summon item ~ ~-5 ~ {Item:{id:smoker}}
summon item ~ ~-5 ~ {Item:{id:blast_furnace}}
summon item ~ ~-5 ~ {Item:{id:campfire}}
summon item ~ ~-5 ~ {Item:{id:soul_campfire}}
summon item ~ ~-5 ~ {Item:{id:anvil}}
summon item ~ ~-5 ~ {Item:{id:chipped_anvil}}
summon item ~ ~-5 ~ {Item:{id:damaged_anvil}}
summon item ~ ~-5 ~ {Item:{id:composter}}
summon item ~ ~-5 ~ {Item:{id:note_block}}
summon item ~ ~-5 ~ {Item:{id:jukebox}}
summon item ~ ~-5 ~ {Item:{id:enchanting_table}}
summon item ~ ~-5 ~ {Item:{id:end_crystal}}
summon item ~ ~-5 ~ {Item:{id:brewing_stand}}
summon item ~ ~-5 ~ {Item:{id:cauldron}}
summon item ~ ~-5 ~ {Item:{id:bell}}
summon item ~ ~-5 ~ {Item:{id:beacon}}
summon item ~ ~-5 ~ {Item:{id:conduit}}
summon item ~ ~-5 ~ {Item:{id:lodestone}}
summon item ~ ~-5 ~ {Item:{id:ladder}}
summon item ~ ~-5 ~ {Item:{id:scaffolding}}
summon item ~ ~-5 ~ {Item:{id:bee_nest}}
summon item ~ ~-5 ~ {Item:{id:beehive}}
summon item ~ ~-5 ~ {Item:{id:suspicious_sand}}
summon item ~ ~-5 ~ {Item:{id:suspicious_gravel}}
summon item ~ ~-5 ~ {Item:{id:lightning_rod}}
summon item ~ ~-5 ~ {Item:{id:flower_pot}}
summon item ~ ~-5 ~ {Item:{id:decorated_pot}}
summon item ~ ~-5 ~ {Item:{id:armor_stand}}
summon item ~ ~-5 ~ {Item:{id:item_frame}}
summon item ~ ~-5 ~ {Item:{id:glow_item_frame}}
summon item ~ ~-5 ~ {Item:{id:painting}}
summon item ~ ~-5 ~ {Item:{id:bookshelf}}
summon item ~ ~-5 ~ {Item:{id:chiseled_bookshelf}}
summon item ~ ~-5 ~ {Item:{id:lectern}}
summon item ~ ~-5 ~ {Item:{id:tinted_glass}}
summon item ~ ~-5 ~ {Item:{id:oak_sign}}
summon item ~ ~-5 ~ {Item:{id:oak_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:spruce_sign}}
summon item ~ ~-5 ~ {Item:{id:spruce_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:birch_sign}}
summon item ~ ~-5 ~ {Item:{id:birch_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:jungle_sign}}
summon item ~ ~-5 ~ {Item:{id:jungle_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:acacia_sign}}
summon item ~ ~-5 ~ {Item:{id:acacia_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_sign}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:mangrove_sign}}
summon item ~ ~-5 ~ {Item:{id:mangrove_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:cherry_sign}}
summon item ~ ~-5 ~ {Item:{id:cherry_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_sign}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:bamboo_sign}}
summon item ~ ~-5 ~ {Item:{id:bamboo_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:crimson_sign}}
summon item ~ ~-5 ~ {Item:{id:crimson_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:warped_sign}}
summon item ~ ~-5 ~ {Item:{id:warped_hanging_sign}}
summon item ~ ~-5 ~ {Item:{id:chest}}
summon item ~ ~-5 ~ {Item:{id:barrel}}
summon item ~ ~-5 ~ {Item:{id:ender_chest}}
summon item ~ ~-5 ~ {Item:{id:shulker_box}}
summon item ~ ~-5 ~ {Item:{id:white_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:light_gray_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:gray_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:black_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:brown_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:red_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:orange_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:yellow_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:lime_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:green_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:cyan_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:light_blue_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:blue_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:purple_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:magenta_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:pink_shulker_box}}
summon item ~ ~-5 ~ {Item:{id:respawn_anchor}}
summon item ~ ~-5 ~ {Item:{id:white_bed}}
summon item ~ ~-5 ~ {Item:{id:light_gray_bed}}
summon item ~ ~-5 ~ {Item:{id:gray_bed}}
summon item ~ ~-5 ~ {Item:{id:black_bed}}
summon item ~ ~-5 ~ {Item:{id:brown_bed}}
summon item ~ ~-5 ~ {Item:{id:red_bed}}
summon item ~ ~-5 ~ {Item:{id:orange_bed}}
summon item ~ ~-5 ~ {Item:{id:yellow_bed}}
summon item ~ ~-5 ~ {Item:{id:lime_bed}}
summon item ~ ~-5 ~ {Item:{id:green_bed}}
summon item ~ ~-5 ~ {Item:{id:cyan_bed}}
summon item ~ ~-5 ~ {Item:{id:light_blue_bed}}
summon item ~ ~-5 ~ {Item:{id:blue_bed}}
summon item ~ ~-5 ~ {Item:{id:purple_bed}}
summon item ~ ~-5 ~ {Item:{id:magenta_bed}}
summon item ~ ~-5 ~ {Item:{id:pink_bed}}
summon item ~ ~-5 ~ {Item:{id:candle}}
summon item ~ ~-5 ~ {Item:{id:white_candle}}
summon item ~ ~-5 ~ {Item:{id:light_gray_candle}}
summon item ~ ~-5 ~ {Item:{id:gray_candle}}
summon item ~ ~-5 ~ {Item:{id:black_candle}}
summon item ~ ~-5 ~ {Item:{id:brown_candle}}
summon item ~ ~-5 ~ {Item:{id:red_candle}}
summon item ~ ~-5 ~ {Item:{id:orange_candle}}
summon item ~ ~-5 ~ {Item:{id:yellow_candle}}
summon item ~ ~-5 ~ {Item:{id:lime_candle}}
summon item ~ ~-5 ~ {Item:{id:green_candle}}
summon item ~ ~-5 ~ {Item:{id:cyan_candle}}
summon item ~ ~-5 ~ {Item:{id:light_blue_candle}}
summon item ~ ~-5 ~ {Item:{id:blue_candle}}
summon item ~ ~-5 ~ {Item:{id:purple_candle}}
summon item ~ ~-5 ~ {Item:{id:magenta_candle}}
summon item ~ ~-5 ~ {Item:{id:pink_candle}}
summon item ~ ~-5 ~ {Item:{id:white_banner}}
summon item ~ ~-5 ~ {Item:{id:light_gray_banner}}
summon item ~ ~-5 ~ {Item:{id:gray_banner}}
summon item ~ ~-5 ~ {Item:{id:black_banner}}
summon item ~ ~-5 ~ {Item:{id:brown_banner}}
summon item ~ ~-5 ~ {Item:{id:red_banner}}
summon item ~ ~-5 ~ {Item:{id:orange_banner}}
summon item ~ ~-5 ~ {Item:{id:yellow_banner}}
summon item ~ ~-5 ~ {Item:{id:lime_banner}}
summon item ~ ~-5 ~ {Item:{id:green_banner}}
summon item ~ ~-5 ~ {Item:{id:cyan_banner}}
summon item ~ ~-5 ~ {Item:{id:light_blue_banner}}
summon item ~ ~-5 ~ {Item:{id:blue_banner}}
summon item ~ ~-5 ~ {Item:{id:purple_banner}}
summon item ~ ~-5 ~ {Item:{id:magenta_banner}}
summon item ~ ~-5 ~ {Item:{id:pink_banner}}
summon item ~ ~-5 ~ {Item:{id:skeleton_skull}}
summon item ~ ~-5 ~ {Item:{id:wither_skeleton_skull}}
summon item ~ ~-5 ~ {Item:{id:player_head}}
summon item ~ ~-5 ~ {Item:{id:zombie_head}}
summon item ~ ~-5 ~ {Item:{id:creeper_head}}
summon item ~ ~-5 ~ {Item:{id:piglin_head}}
summon item ~ ~-5 ~ {Item:{id:dragon_head}}
summon item ~ ~-5 ~ {Item:{id:dragon_egg}}
summon item ~ ~-5 ~ {Item:{id:end_portal_frame}}
summon item ~ ~-5 ~ {Item:{id:ender_eye}}
summon item ~ ~-5 ~ {Item:{id:vault}}
summon item ~ ~-5 ~ {Item:{id:infested_stone}}
summon item ~ ~-5 ~ {Item:{id:infested_cobblestone}}
summon item ~ ~-5 ~ {Item:{id:infested_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:infested_mossy_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:infested_cracked_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:infested_chiseled_stone_bricks}}
summon item ~ ~-5 ~ {Item:{id:infested_deepslate}}
summon item ~ ~-5 ~ {Item:{id:redstone}}
summon item ~ ~-5 ~ {Item:{id:redstone_torch}}
summon item ~ ~-5 ~ {Item:{id:redstone_block}}
summon item ~ ~-5 ~ {Item:{id:repeater}}
summon item ~ ~-5 ~ {Item:{id:comparator}}
summon item ~ ~-5 ~ {Item:{id:target}}
summon item ~ ~-5 ~ {Item:{id:waxed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_exposed_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_weathered_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:waxed_oxidized_copper_bulb}}
summon item ~ ~-5 ~ {Item:{id:lever}}
summon item ~ ~-5 ~ {Item:{id:oak_button}}
summon item ~ ~-5 ~ {Item:{id:stone_button}}
summon item ~ ~-5 ~ {Item:{id:oak_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:stone_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:light_weighted_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:heavy_weighted_pressure_plate}}
summon item ~ ~-5 ~ {Item:{id:sculk_sensor}}
summon item ~ ~-5 ~ {Item:{id:calibrated_sculk_sensor}}
summon item ~ ~-5 ~ {Item:{id:sculk_shrieker}}
summon item ~ ~-5 ~ {Item:{id:amethyst_block}}
summon item ~ ~-5 ~ {Item:{id:white_wool}}
summon item ~ ~-5 ~ {Item:{id:tripwire_hook}}
summon item ~ ~-5 ~ {Item:{id:string}}
summon item ~ ~-5 ~ {Item:{id:lectern}}
summon item ~ ~-5 ~ {Item:{id:daylight_detector}}
summon item ~ ~-5 ~ {Item:{id:lightning_rod}}
summon item ~ ~-5 ~ {Item:{id:piston}}
summon item ~ ~-5 ~ {Item:{id:sticky_piston}}
summon item ~ ~-5 ~ {Item:{id:slime_block}}
summon item ~ ~-5 ~ {Item:{id:honey_block}}
summon item ~ ~-5 ~ {Item:{id:dispenser}}
summon item ~ ~-5 ~ {Item:{id:dropper}}
summon item ~ ~-5 ~ {Item:{id:crafter}}
summon item ~ ~-5 ~ {Item:{id:hopper}}
summon item ~ ~-5 ~ {Item:{id:chest}}
summon item ~ ~-5 ~ {Item:{id:barrel}}
summon item ~ ~-5 ~ {Item:{id:chiseled_bookshelf}}
summon item ~ ~-5 ~ {Item:{id:furnace}}
summon item ~ ~-5 ~ {Item:{id:trapped_chest}}
summon item ~ ~-5 ~ {Item:{id:jukebox}}
summon item ~ ~-5 ~ {Item:{id:decorated_pot}}
summon item ~ ~-5 ~ {Item:{id:observer}}
summon item ~ ~-5 ~ {Item:{id:note_block}}
summon item ~ ~-5 ~ {Item:{id:composter}}
summon item ~ ~-5 ~ {Item:{id:cauldron}}
summon item ~ ~-5 ~ {Item:{id:rail}}
summon item ~ ~-5 ~ {Item:{id:powered_rail}}
summon item ~ ~-5 ~ {Item:{id:detector_rail}}
summon item ~ ~-5 ~ {Item:{id:activator_rail}}
summon item ~ ~-5 ~ {Item:{id:minecart}}
summon item ~ ~-5 ~ {Item:{id:hopper_minecart}}
summon item ~ ~-5 ~ {Item:{id:chest_minecart}}
summon item ~ ~-5 ~ {Item:{id:furnace_minecart}}
summon item ~ ~-5 ~ {Item:{id:tnt_minecart}}
summon item ~ ~-5 ~ {Item:{id:oak_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:bamboo_chest_raft}}
summon item ~ ~-5 ~ {Item:{id:oak_door}}
summon item ~ ~-5 ~ {Item:{id:iron_door}}
summon item ~ ~-5 ~ {Item:{id:oak_fence_gate}}
summon item ~ ~-5 ~ {Item:{id:oak_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:iron_trapdoor}}
summon item ~ ~-5 ~ {Item:{id:tnt}}
summon item ~ ~-5 ~ {Item:{id:redstone_lamp}}
summon item ~ ~-5 ~ {Item:{id:bell}}
summon item ~ ~-5 ~ {Item:{id:big_dripleaf}}
summon item ~ ~-5 ~ {Item:{id:armor_stand}}
summon item ~ ~-5 ~ {Item:{id:redstone_ore}}
summon item ~ ~-5 ~ {Item:{id:wooden_shovel}}
summon item ~ ~-5 ~ {Item:{id:wooden_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:wooden_axe}}
summon item ~ ~-5 ~ {Item:{id:wooden_hoe}}
summon item ~ ~-5 ~ {Item:{id:stone_shovel}}
summon item ~ ~-5 ~ {Item:{id:stone_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:stone_axe}}
summon item ~ ~-5 ~ {Item:{id:stone_hoe}}
summon item ~ ~-5 ~ {Item:{id:iron_shovel}}
summon item ~ ~-5 ~ {Item:{id:iron_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:iron_axe}}
summon item ~ ~-5 ~ {Item:{id:iron_hoe}}
summon item ~ ~-5 ~ {Item:{id:golden_shovel}}
summon item ~ ~-5 ~ {Item:{id:golden_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:golden_axe}}
summon item ~ ~-5 ~ {Item:{id:golden_hoe}}
summon item ~ ~-5 ~ {Item:{id:diamond_shovel}}
summon item ~ ~-5 ~ {Item:{id:diamond_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:diamond_axe}}
summon item ~ ~-5 ~ {Item:{id:diamond_hoe}}
summon item ~ ~-5 ~ {Item:{id:netherite_shovel}}
summon item ~ ~-5 ~ {Item:{id:netherite_pickaxe}}
summon item ~ ~-5 ~ {Item:{id:netherite_axe}}
summon item ~ ~-5 ~ {Item:{id:netherite_hoe}}
summon item ~ ~-5 ~ {Item:{id:bucket}}
summon item ~ ~-5 ~ {Item:{id:water_bucket}}
summon item ~ ~-5 ~ {Item:{id:cod_bucket}}
summon item ~ ~-5 ~ {Item:{id:salmon_bucket}}
summon item ~ ~-5 ~ {Item:{id:tropical_fish_bucket}}
summon item ~ ~-5 ~ {Item:{id:pufferfish_bucket}}
summon item ~ ~-5 ~ {Item:{id:axolotl_bucket}}
summon item ~ ~-5 ~ {Item:{id:tadpole_bucket}}
summon item ~ ~-5 ~ {Item:{id:lava_bucket}}
summon item ~ ~-5 ~ {Item:{id:powder_snow_bucket}}
summon item ~ ~-5 ~ {Item:{id:milk_bucket}}
summon item ~ ~-5 ~ {Item:{id:fishing_rod}}
summon item ~ ~-5 ~ {Item:{id:flint_and_steel}}
summon item ~ ~-5 ~ {Item:{id:fire_charge}}
summon item ~ ~-5 ~ {Item:{id:bone_meal}}
summon item ~ ~-5 ~ {Item:{id:shears}}
summon item ~ ~-5 ~ {Item:{id:brush}}
summon item ~ ~-5 ~ {Item:{id:name_tag}}
summon item ~ ~-5 ~ {Item:{id:lead}}
summon item ~ ~-5 ~ {Item:{id:bundle}}
summon item ~ ~-5 ~ {Item:{id:white_bundle}}
summon item ~ ~-5 ~ {Item:{id:light_gray_bundle}}
summon item ~ ~-5 ~ {Item:{id:gray_bundle}}
summon item ~ ~-5 ~ {Item:{id:black_bundle}}
summon item ~ ~-5 ~ {Item:{id:brown_bundle}}
summon item ~ ~-5 ~ {Item:{id:red_bundle}}
summon item ~ ~-5 ~ {Item:{id:orange_bundle}}
summon item ~ ~-5 ~ {Item:{id:yellow_bundle}}
summon item ~ ~-5 ~ {Item:{id:lime_bundle}}
summon item ~ ~-5 ~ {Item:{id:green_bundle}}
summon item ~ ~-5 ~ {Item:{id:cyan_bundle}}
summon item ~ ~-5 ~ {Item:{id:light_blue_bundle}}
summon item ~ ~-5 ~ {Item:{id:blue_bundle}}
summon item ~ ~-5 ~ {Item:{id:purple_bundle}}
summon item ~ ~-5 ~ {Item:{id:magenta_bundle}}
summon item ~ ~-5 ~ {Item:{id:pink_bundle}}
summon item ~ ~-5 ~ {Item:{id:compass}}
summon item ~ ~-5 ~ {Item:{id:recovery_compass}}
summon item ~ ~-5 ~ {Item:{id:clock}}
summon item ~ ~-5 ~ {Item:{id:spyglass}}
summon item ~ ~-5 ~ {Item:{id:map}}
summon item ~ ~-5 ~ {Item:{id:writable_book}}
summon item ~ ~-5 ~ {Item:{id:wind_charge}}
summon item ~ ~-5 ~ {Item:{id:ender_pearl}}
summon item ~ ~-5 ~ {Item:{id:ender_eye}}
summon item ~ ~-5 ~ {Item:{id:elytra}}
summon item ~ ~-5 ~ {Item:{id:saddle}}
summon item ~ ~-5 ~ {Item:{id:white_harness}}
summon item ~ ~-5 ~ {Item:{id:light_gray_harness}}
summon item ~ ~-5 ~ {Item:{id:gray_harness}}
summon item ~ ~-5 ~ {Item:{id:black_harness}}
summon item ~ ~-5 ~ {Item:{id:brown_harness}}
summon item ~ ~-5 ~ {Item:{id:red_harness}}
summon item ~ ~-5 ~ {Item:{id:orange_harness}}
summon item ~ ~-5 ~ {Item:{id:yellow_harness}}
summon item ~ ~-5 ~ {Item:{id:lime_harness}}
summon item ~ ~-5 ~ {Item:{id:green_harness}}
summon item ~ ~-5 ~ {Item:{id:cyan_harness}}
summon item ~ ~-5 ~ {Item:{id:light_blue_harness}}
summon item ~ ~-5 ~ {Item:{id:blue_harness}}
summon item ~ ~-5 ~ {Item:{id:purple_harness}}
summon item ~ ~-5 ~ {Item:{id:magenta_harness}}
summon item ~ ~-5 ~ {Item:{id:pink_harness}}
summon item ~ ~-5 ~ {Item:{id:carrot_on_a_stick}}
summon item ~ ~-5 ~ {Item:{id:warped_fungus_on_a_stick}}
summon item ~ ~-5 ~ {Item:{id:oak_boat}}
summon item ~ ~-5 ~ {Item:{id:oak_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:spruce_boat}}
summon item ~ ~-5 ~ {Item:{id:spruce_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:birch_boat}}
summon item ~ ~-5 ~ {Item:{id:birch_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:jungle_boat}}
summon item ~ ~-5 ~ {Item:{id:jungle_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:acacia_boat}}
summon item ~ ~-5 ~ {Item:{id:acacia_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_boat}}
summon item ~ ~-5 ~ {Item:{id:dark_oak_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:mangrove_boat}}
summon item ~ ~-5 ~ {Item:{id:mangrove_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:cherry_boat}}
summon item ~ ~-5 ~ {Item:{id:cherry_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_boat}}
summon item ~ ~-5 ~ {Item:{id:pale_oak_chest_boat}}
summon item ~ ~-5 ~ {Item:{id:bamboo_raft}}
summon item ~ ~-5 ~ {Item:{id:bamboo_chest_raft}}
summon item ~ ~-5 ~ {Item:{id:rail}}
summon item ~ ~-5 ~ {Item:{id:powered_rail}}
summon item ~ ~-5 ~ {Item:{id:detector_rail}}
summon item ~ ~-5 ~ {Item:{id:activator_rail}}
summon item ~ ~-5 ~ {Item:{id:minecart}}
summon item ~ ~-5 ~ {Item:{id:hopper_minecart}}
summon item ~ ~-5 ~ {Item:{id:chest_minecart}}
summon item ~ ~-5 ~ {Item:{id:furnace_minecart}}
summon item ~ ~-5 ~ {Item:{id:tnt_minecart}}
summon item ~ ~-5 ~ {Item:{id:music_disc_13}}
summon item ~ ~-5 ~ {Item:{id:music_disc_cat}}
summon item ~ ~-5 ~ {Item:{id:music_disc_blocks}}
summon item ~ ~-5 ~ {Item:{id:music_disc_chirp}}
summon item ~ ~-5 ~ {Item:{id:music_disc_far}}
summon item ~ ~-5 ~ {Item:{id:music_disc_mall}}
summon item ~ ~-5 ~ {Item:{id:music_disc_mellohi}}
summon item ~ ~-5 ~ {Item:{id:music_disc_stal}}
summon item ~ ~-5 ~ {Item:{id:music_disc_strad}}
summon item ~ ~-5 ~ {Item:{id:music_disc_ward}}
summon item ~ ~-5 ~ {Item:{id:music_disc_11}}
summon item ~ ~-5 ~ {Item:{id:music_disc_creator_music_box}}
summon item ~ ~-5 ~ {Item:{id:music_disc_wait}}
summon item ~ ~-5 ~ {Item:{id:music_disc_creator}}
summon item ~ ~-5 ~ {Item:{id:music_disc_precipice}}
summon item ~ ~-5 ~ {Item:{id:music_disc_otherside}}
summon item ~ ~-5 ~ {Item:{id:music_disc_relic}}
summon item ~ ~-5 ~ {Item:{id:music_disc_5}}
summon item ~ ~-5 ~ {Item:{id:music_disc_pigstep}}
summon item ~ ~-5 ~ {Item:{id:music_disc_tears}}
summon item ~ ~-5 ~ {Item:{id:music_disc_lava_chicken}}
summon item ~ ~-5 ~ {Item:{id:wooden_sword}}
summon item ~ ~-5 ~ {Item:{id:stone_sword}}
summon item ~ ~-5 ~ {Item:{id:iron_sword}}
summon item ~ ~-5 ~ {Item:{id:golden_sword}}
summon item ~ ~-5 ~ {Item:{id:diamond_sword}}
summon item ~ ~-5 ~ {Item:{id:netherite_sword}}
summon item ~ ~-5 ~ {Item:{id:wooden_axe}}
summon item ~ ~-5 ~ {Item:{id:stone_axe}}
summon item ~ ~-5 ~ {Item:{id:iron_axe}}
summon item ~ ~-5 ~ {Item:{id:golden_axe}}
summon item ~ ~-5 ~ {Item:{id:diamond_axe}}
summon item ~ ~-5 ~ {Item:{id:netherite_axe}}
summon item ~ ~-5 ~ {Item:{id:trident}}
summon item ~ ~-5 ~ {Item:{id:mace}}
summon item ~ ~-5 ~ {Item:{id:shield}}
summon item ~ ~-5 ~ {Item:{id:leather_helmet}}
summon item ~ ~-5 ~ {Item:{id:leather_chestplate}}
summon item ~ ~-5 ~ {Item:{id:leather_leggings}}
summon item ~ ~-5 ~ {Item:{id:leather_boots}}
summon item ~ ~-5 ~ {Item:{id:chainmail_helmet}}
summon item ~ ~-5 ~ {Item:{id:chainmail_chestplate}}
summon item ~ ~-5 ~ {Item:{id:chainmail_leggings}}
summon item ~ ~-5 ~ {Item:{id:chainmail_boots}}
summon item ~ ~-5 ~ {Item:{id:iron_helmet}}
summon item ~ ~-5 ~ {Item:{id:iron_chestplate}}
summon item ~ ~-5 ~ {Item:{id:iron_leggings}}
summon item ~ ~-5 ~ {Item:{id:iron_boots}}
summon item ~ ~-5 ~ {Item:{id:golden_helmet}}
summon item ~ ~-5 ~ {Item:{id:golden_chestplate}}
summon item ~ ~-5 ~ {Item:{id:golden_leggings}}
summon item ~ ~-5 ~ {Item:{id:golden_boots}}
summon item ~ ~-5 ~ {Item:{id:diamond_helmet}}
summon item ~ ~-5 ~ {Item:{id:diamond_chestplate}}
summon item ~ ~-5 ~ {Item:{id:diamond_leggings}}
summon item ~ ~-5 ~ {Item:{id:diamond_boots}}
summon item ~ ~-5 ~ {Item:{id:netherite_helmet}}
summon item ~ ~-5 ~ {Item:{id:netherite_chestplate}}
summon item ~ ~-5 ~ {Item:{id:netherite_leggings}}
summon item ~ ~-5 ~ {Item:{id:netherite_boots}}
summon item ~ ~-5 ~ {Item:{id:turtle_helmet}}
summon item ~ ~-5 ~ {Item:{id:leather_horse_armor}}
summon item ~ ~-5 ~ {Item:{id:iron_horse_armor}}
summon item ~ ~-5 ~ {Item:{id:golden_horse_armor}}
summon item ~ ~-5 ~ {Item:{id:diamond_horse_armor}}
summon item ~ ~-5 ~ {Item:{id:wolf_armor}}
summon item ~ ~-5 ~ {Item:{id:totem_of_undying}}
summon item ~ ~-5 ~ {Item:{id:tnt}}
summon item ~ ~-5 ~ {Item:{id:end_crystal}}
summon item ~ ~-5 ~ {Item:{id:snowball}}
summon item ~ ~-5 ~ {Item:{id:egg}}
summon item ~ ~-5 ~ {Item:{id:brown_egg}}
summon item ~ ~-5 ~ {Item:{id:blue_egg}}
summon item ~ ~-5 ~ {Item:{id:wind_charge}}
summon item ~ ~-5 ~ {Item:{id:bow}}
summon item ~ ~-5 ~ {Item:{id:crossbow}}
summon item ~ ~-5 ~ {Item:{id:arrow}}
summon item ~ ~-5 ~ {Item:{id:spectral_arrow}}
summon item ~ ~-5 ~ {Item:{id:apple}}
summon item ~ ~-5 ~ {Item:{id:golden_apple}}
summon item ~ ~-5 ~ {Item:{id:enchanted_golden_apple}}
summon item ~ ~-5 ~ {Item:{id:melon_slice}}
summon item ~ ~-5 ~ {Item:{id:sweet_berries}}
summon item ~ ~-5 ~ {Item:{id:glow_berries}}
summon item ~ ~-5 ~ {Item:{id:chorus_fruit}}
summon item ~ ~-5 ~ {Item:{id:carrot}}
summon item ~ ~-5 ~ {Item:{id:golden_carrot}}
summon item ~ ~-5 ~ {Item:{id:potato}}
summon item ~ ~-5 ~ {Item:{id:baked_potato}}
summon item ~ ~-5 ~ {Item:{id:poisonous_potato}}
summon item ~ ~-5 ~ {Item:{id:beetroot}}
summon item ~ ~-5 ~ {Item:{id:dried_kelp}}
summon item ~ ~-5 ~ {Item:{id:beef}}
summon item ~ ~-5 ~ {Item:{id:cooked_beef}}
summon item ~ ~-5 ~ {Item:{id:porkchop}}
summon item ~ ~-5 ~ {Item:{id:cooked_porkchop}}
summon item ~ ~-5 ~ {Item:{id:mutton}}
summon item ~ ~-5 ~ {Item:{id:cooked_mutton}}
summon item ~ ~-5 ~ {Item:{id:chicken}}
summon item ~ ~-5 ~ {Item:{id:cooked_chicken}}
summon item ~ ~-5 ~ {Item:{id:rabbit}}
summon item ~ ~-5 ~ {Item:{id:cooked_rabbit}}
summon item ~ ~-5 ~ {Item:{id:cod}}
summon item ~ ~-5 ~ {Item:{id:cooked_cod}}
summon item ~ ~-5 ~ {Item:{id:salmon}}
summon item ~ ~-5 ~ {Item:{id:cooked_salmon}}
summon item ~ ~-5 ~ {Item:{id:tropical_fish}}
summon item ~ ~-5 ~ {Item:{id:pufferfish}}
summon item ~ ~-5 ~ {Item:{id:bread}}
summon item ~ ~-5 ~ {Item:{id:cookie}}
summon item ~ ~-5 ~ {Item:{id:cake}}
summon item ~ ~-5 ~ {Item:{id:pumpkin_pie}}
summon item ~ ~-5 ~ {Item:{id:rotten_flesh}}
summon item ~ ~-5 ~ {Item:{id:spider_eye}}
summon item ~ ~-5 ~ {Item:{id:mushroom_stew}}
summon item ~ ~-5 ~ {Item:{id:beetroot_soup}}
summon item ~ ~-5 ~ {Item:{id:rabbit_stew}}
summon item ~ ~-5 ~ {Item:{id:milk_bucket}}
summon item ~ ~-5 ~ {Item:{id:honey_bottle}}
summon item ~ ~-5 ~ {Item:{id:coal}}
summon item ~ ~-5 ~ {Item:{id:charcoal}}
summon item ~ ~-5 ~ {Item:{id:raw_iron}}
summon item ~ ~-5 ~ {Item:{id:raw_copper}}
summon item ~ ~-5 ~ {Item:{id:raw_gold}}
summon item ~ ~-5 ~ {Item:{id:emerald}}
summon item ~ ~-5 ~ {Item:{id:lapis_lazuli}}
summon item ~ ~-5 ~ {Item:{id:diamond}}
summon item ~ ~-5 ~ {Item:{id:ancient_debris}}
summon item ~ ~-5 ~ {Item:{id:quartz}}
summon item ~ ~-5 ~ {Item:{id:amethyst_shard}}
summon item ~ ~-5 ~ {Item:{id:iron_nugget}}
summon item ~ ~-5 ~ {Item:{id:gold_nugget}}
summon item ~ ~-5 ~ {Item:{id:iron_ingot}}
summon item ~ ~-5 ~ {Item:{id:copper_ingot}}
summon item ~ ~-5 ~ {Item:{id:gold_ingot}}
summon item ~ ~-5 ~ {Item:{id:netherite_scrap}}
summon item ~ ~-5 ~ {Item:{id:netherite_ingot}}
summon item ~ ~-5 ~ {Item:{id:stick}}
summon item ~ ~-5 ~ {Item:{id:flint}}
summon item ~ ~-5 ~ {Item:{id:wheat}}
summon item ~ ~-5 ~ {Item:{id:bone}}
summon item ~ ~-5 ~ {Item:{id:bone_meal}}
summon item ~ ~-5 ~ {Item:{id:string}}
summon item ~ ~-5 ~ {Item:{id:feather}}
summon item ~ ~-5 ~ {Item:{id:snowball}}
summon item ~ ~-5 ~ {Item:{id:egg}}
summon item ~ ~-5 ~ {Item:{id:brown_egg}}
summon item ~ ~-5 ~ {Item:{id:blue_egg}}
summon item ~ ~-5 ~ {Item:{id:leather}}
summon item ~ ~-5 ~ {Item:{id:rabbit_hide}}
summon item ~ ~-5 ~ {Item:{id:honeycomb}}
summon item ~ ~-5 ~ {Item:{id:resin_clump}}
summon item ~ ~-5 ~ {Item:{id:ink_sac}}
summon item ~ ~-5 ~ {Item:{id:glow_ink_sac}}
summon item ~ ~-5 ~ {Item:{id:turtle_scute}}
summon item ~ ~-5 ~ {Item:{id:armadillo_scute}}
summon item ~ ~-5 ~ {Item:{id:slime_ball}}
summon item ~ ~-5 ~ {Item:{id:clay_ball}}
summon item ~ ~-5 ~ {Item:{id:prismarine_shard}}
summon item ~ ~-5 ~ {Item:{id:prismarine_crystals}}
summon item ~ ~-5 ~ {Item:{id:nautilus_shell}}
summon item ~ ~-5 ~ {Item:{id:heart_of_the_sea}}
summon item ~ ~-5 ~ {Item:{id:fire_charge}}
summon item ~ ~-5 ~ {Item:{id:blaze_rod}}
summon item ~ ~-5 ~ {Item:{id:breeze_rod}}
summon item ~ ~-5 ~ {Item:{id:heavy_core}}
summon item ~ ~-5 ~ {Item:{id:nether_star}}
summon item ~ ~-5 ~ {Item:{id:ender_pearl}}
summon item ~ ~-5 ~ {Item:{id:ender_eye}}
summon item ~ ~-5 ~ {Item:{id:shulker_shell}}
summon item ~ ~-5 ~ {Item:{id:popped_chorus_fruit}}
summon item ~ ~-5 ~ {Item:{id:echo_shard}}
summon item ~ ~-5 ~ {Item:{id:disc_fragment_5}}
summon item ~ ~-5 ~ {Item:{id:white_dye}}
summon item ~ ~-5 ~ {Item:{id:light_gray_dye}}
summon item ~ ~-5 ~ {Item:{id:gray_dye}}
summon item ~ ~-5 ~ {Item:{id:black_dye}}
summon item ~ ~-5 ~ {Item:{id:brown_dye}}
summon item ~ ~-5 ~ {Item:{id:red_dye}}
summon item ~ ~-5 ~ {Item:{id:orange_dye}}
summon item ~ ~-5 ~ {Item:{id:yellow_dye}}
summon item ~ ~-5 ~ {Item:{id:lime_dye}}
summon item ~ ~-5 ~ {Item:{id:green_dye}}
summon item ~ ~-5 ~ {Item:{id:cyan_dye}}
summon item ~ ~-5 ~ {Item:{id:light_blue_dye}}
summon item ~ ~-5 ~ {Item:{id:blue_dye}}
summon item ~ ~-5 ~ {Item:{id:purple_dye}}
summon item ~ ~-5 ~ {Item:{id:magenta_dye}}
summon item ~ ~-5 ~ {Item:{id:pink_dye}}
summon item ~ ~-5 ~ {Item:{id:bowl}}
summon item ~ ~-5 ~ {Item:{id:brick}}
summon item ~ ~-5 ~ {Item:{id:nether_brick}}
summon item ~ ~-5 ~ {Item:{id:resin_brick}}
summon item ~ ~-5 ~ {Item:{id:paper}}
summon item ~ ~-5 ~ {Item:{id:book}}
summon item ~ ~-5 ~ {Item:{id:firework_star}}
summon item ~ ~-5 ~ {Item:{id:glass_bottle}}
summon item ~ ~-5 ~ {Item:{id:nether_wart}}
summon item ~ ~-5 ~ {Item:{id:redstone}}
summon item ~ ~-5 ~ {Item:{id:glowstone_dust}}
summon item ~ ~-5 ~ {Item:{id:gunpowder}}
summon item ~ ~-5 ~ {Item:{id:dragon_breath}}
summon item ~ ~-5 ~ {Item:{id:fermented_spider_eye}}
summon item ~ ~-5 ~ {Item:{id:blaze_powder}}
summon item ~ ~-5 ~ {Item:{id:sugar}}
summon item ~ ~-5 ~ {Item:{id:rabbit_foot}}
summon item ~ ~-5 ~ {Item:{id:glistering_melon_slice}}
summon item ~ ~-5 ~ {Item:{id:spider_eye}}
summon item ~ ~-5 ~ {Item:{id:pufferfish}}
summon item ~ ~-5 ~ {Item:{id:magma_cream}}
summon item ~ ~-5 ~ {Item:{id:golden_carrot}}
summon item ~ ~-5 ~ {Item:{id:ghast_tear}}
summon item ~ ~-5 ~ {Item:{id:turtle_helmet}}
summon item ~ ~-5 ~ {Item:{id:phantom_membrane}}
summon item ~ ~-5 ~ {Item:{id:field_masoned_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:bordure_indented_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:flower_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:creeper_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:skull_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:mojang_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:globe_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:piglin_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:flow_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:guster_banner_pattern}}
summon item ~ ~-5 ~ {Item:{id:angler_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:archer_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:arms_up_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:blade_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:brewer_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:burn_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:danger_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:explorer_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:flow_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:friend_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:guster_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:heart_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:heartbreak_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:howl_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:miner_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:mourner_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:plenty_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:prize_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:scrape_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:sheaf_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:shelter_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:skull_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:snort_pottery_sherd}}
summon item ~ ~-5 ~ {Item:{id:netherite_upgrade_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:sentry_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:vex_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:wild_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:coast_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:dune_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:wayfinder_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:raiser_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:shaper_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:host_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:ward_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:silence_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:tide_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:snout_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:rib_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:eye_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:spire_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:flow_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:bolt_armor_trim_smithing_template}}
summon item ~ ~-5 ~ {Item:{id:experience_bottle}}
summon item ~ ~-5 ~ {Item:{id:trial_key}}
summon item ~ ~-5 ~ {Item:{id:ominous_trial_key}}
summon item ~ ~-5 ~ {Item:{id:spawner}}
summon item ~ ~-5 ~ {Item:{id:trial_spawner}}
summon item ~ ~-5 ~ {Item:{id:creaking_heart}}
summon item ~ ~-5 ~ {Item:{id:allay_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:armadillo_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:axolotl_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:bat_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:bee_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:blaze_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:bogged_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:breeze_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:camel_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:cat_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:cave_spider_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:chicken_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:cod_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:cow_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:creaking_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:creeper_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:dolphin_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:donkey_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:drowned_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:elder_guardian_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:enderman_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:endermite_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:evoker_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:fox_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:frog_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:ghast_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:glow_squid_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:goat_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:guardian_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:happy_ghast_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:hoglin_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:horse_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:husk_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:iron_golem_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:llama_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:magma_cube_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:mooshroom_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:mule_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:ocelot_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:panda_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:parrot_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:phantom_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:pig_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:piglin_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:piglin_brute_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:pillager_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:polar_bear_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:pufferfish_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:rabbit_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:ravager_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:salmon_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:sheep_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:shulker_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:silverfish_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:skeleton_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:skeleton_horse_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:slime_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:sniffer_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:snow_golem_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:spider_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:squid_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:stray_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:strider_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:tadpole_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:trader_llama_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:tropical_fish_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:turtle_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:vex_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:villager_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:vindicator_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:wandering_trader_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:warden_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:witch_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:wither_skeleton_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:wolf_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:zoglin_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:zombie_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:zombie_horse_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:zombie_villager_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:zombified_piglin_spawn_egg}}
summon item ~ ~-5 ~ {Item:{id:command_block}}
summon item ~ ~-5 ~ {Item:{id:chain_command_block}}
summon item ~ ~-5 ~ {Item:{id:repeating_command_block}}
summon item ~ ~-5 ~ {Item:{id:command_block_minecart}}
summon item ~ ~-5 ~ {Item:{id:jigsaw}}
summon item ~ ~-5 ~ {Item:{id:structure_block}}
summon item ~ ~-5 ~ {Item:{id:structure_void}}
summon item ~ ~-5 ~ {Item:{id:barrier}}
